### ISSUE TITLE
Add ifs test data to repo

### ISSUE THREAD

**Issue by goord** [goord/ece2cmor3#1]
We need very coarse-resolution (T21 or so) test data in the repository for ifs2cmor integration tests. The files however do need to contain many output variables (preferably the PRIMAVERA output configuration) so we can use them to test the real-world post-processing and cmorization pipeline.

**Comment by pabretonniere** [comment]
Hi @goord 

I'm using the files from our PRIMAVERA simulations and "interpolate" them to a coarser grid with the following cdo commands. 
`
#conversion of SH files
cdo gp2sp,t21 -sp2gpl sh_3h 3hr/ICMSH$expname+$outputdate
cdo gp2sp,t21 -sp2gpl sh_6h 6hr/ICMSH$expname+$outputdate
#
`

To "interpolate" the GG files, we would need an example of a very coarse gaussian reduced grid. Do you have one (the coarser that I found is a 80x160 or the reduced version of a n128)?

**Comment by klauswyser** [comment]
Why would the test data need to be on a reduced Gauss grid? `cdo -R` doesn't induce an error when it is applied on a regular Gauss grid, it just doesn't do anything. For testing the workflow a gridpoint file on the full Gauss grid would work.

To get a gridpoint file on a N11 grid (corresponding to the T21 spectral grid) you could do

<pre>
# remapping of GG files
cdo -R remapbil,n11 reduced_gg_3h 3hr/ICMGG$expname+$outputdate 
cdo -R remapbil,n11 reduced_gg_6h 6hr/ICMGG$expname+$outputdate
</pre>

@pabretonniere: shouldn't your example above use `gp2spl` instead of `gp2sp`? The further processing cdo will use `sp2gpl`which may result in an error if the spectral truncation is not linear.

**Comment by goord** [comment]
Good ideas, I will do it asap. I will also put my files on the ftp server for you to download them, Pierre-Antoine.

I gave the both of you push permissions to this repo btw.

**Comment by klauswyser** [comment]
I just learned that cdo can chage the spectral resolution with `sp2sp`, thus there is no need to go frist from spectral to gridpoint and then back, but one could just do
<pre>
cdo sp2sp,t21 sh_3h 3hr/ICMSH$expname+$outputdate
</pre>

**Comment by goord** [comment]
Klaus for the gridpoint files we would prefer the test data to be on a reduced gaussian grid. If this turns out impossible, we can add a flag in the code that prevents remapping to a regular grid in the post-processing step (this breaks if the test data is already on a regular grid).

**Comment by klauswyser** [comment]
@goord 
> this breaks if the test data is already on a regular grid

Why would that happen? Don't you use `cdo -R` for the remapping? The `-R ` option doesn't complain if the data already is on a regular Gauss grid. In fact you can a mix of regular and reduced Gauss grids in the same file, and cdo will not complain.

But anyway, if you really want a reduced N21 grid we would need a template for that, and then could follow the [steps outlined at the EC-EARTH dev portal]:(https://dev.ec-earth.org/projects/ecearth3/wiki/Regular_and_reduced_Gauss_grids)

**Comment by klauswyser** [comment]
Sorry, wrong button, diidn't want to close the issue, reopening.

**Comment by klauswyser** [comment]
N32 is the smallest grid that still supports reduction which would correspond to a T63 spectral grid. Here I attach a [grid description file for the reduced N32 grid](https://github.com/goord/ece2cmor3/files/844353/gdes_n32_reduced.txt) that can be used together with `cdo remapbil` 

Note: the grid description file is in DOS format, you may want run it through dos2unix before using it.

It might be good then to also use `sp2sp,t63` for consistency.

**Comment by klauswyser** [comment]
I see that you use the cdo command `setgridtype,regular` to go from the reduced to the regular Gauss grid. The drawback of using this command is that it fails if the input already is n a regular Gauss grid. The better way to solve this is with option `-R`instead. This option can be applied multiple times without problems, even on grids that already are on a regular Gauss grid. The best place for the `-R` option is where you switch from GRIB to netCDF, I assume this is a pretty late stage in the whole processing.

**Comment by goord** [comment]
I thought the -R was deprecated in the newer versions of cdo. By the way, we can not just apply -R at the latest stage Klaus: if we apply a nonlinear time aggregation method first (e.g. daymax or daymin), we need to remap on the regular grid _first_ right, it is not guaranteed that the extrema are preserved under the remapping. These subtleties are taken care off in the cdoapi.py code, where we try to reshuffle cdo operators with such constraints.

**Comment by klauswyser** [comment]
No, `-R` is alive and kicking, I have seen any notion on the deprecation on the cdo Wiki either. The only issue with `-R` is that it only works with GRIB1, but switching to GRIB2 is currently not an issue for EC-EARTH.

But you are right regarding the non-linear diagnostics, the values may change depending on whether the remapping is done before or after. But the question is really what is correct: apply a diagnostics first and then remap, or first remap and the apply the diagnostics. I usually favor the approach to do all diagnostics on the original grid as long as possible, and then just do the remapping at the end to get presentable results. The reason is that remapping will smooth the fields, so doing a remapping (or even worse a series of remapping) will result in less spatial variability.

**Comment by goord** [comment]
Very well, I created issue #17 to do the remapping. I do however assume that the spectral remapping does need to be done before we apply non-linear diagnostics?

**Comment by goord** [comment]
Rev. d6b2e183f3c624ac8b3575ef65b6065d4ef1ea38
