### ISSUE TITLE
Replace setgridtype,regular with -R option

### ISSUE THREAD

**Issue by goord** [goord/ece2cmor3#17]
This will allow us to use regular grid re-interpolated ec-earth output as test data.

**Comment by klauswyser** [comment]
After a 2nd thought I am not so sure any longer that `-R` is the best way to go, the solution with`-setgridtype,regular` has a number of advantages:

- the time whne the reduced grid should be interpolated in a sequence of cdo commands can be exactly controlled with setgridtype while we don't know exactly when it happens with -R (is t the first or last step of the sequence?). This matters because some operations (e.g. non-linear statistics) are better done on the regular grid for consistency, while other non-lineaer operations (e.g. computing the surface albedo from radiation) should be done on the original (reduced) grid. It is an asset to control exactly when the remapping is done.
- -R works only with GRIB1, but we are likely forced to use GRIB2 in the cmorisation. The reason is that the required top most pressure level is 40 Pa which is < 1 hPa. The pressure units in GRIB1 are hPa for pressure levels >= 1 hPa, but Pa for levels < 1 hPa.  Cdo "sees" two different z-axis and therefore treats one and the same variable as two variables in GRIB1. It can be avoided by saving the variable in GRIB2 format instead. For GRIB2 `-R` will not work but `-setgridtype,regular`should (but I haven't tested yet).

**Comment by goord** [comment]
Ok thanks, then I will close this issue. For the test data I will build a flag to switch off the setgridtype,regular. In this way it will become possible to apply the tool on regular gridded data as well.
