### ISSUE TITLE
update for CMOR release 3.2.8

### ISSUE THREAD

**Issue by treerink** [goord/ece2cmor3#72]
Because of the CMOR release 3.2.8 last week, this could be updated in:
environment.yml
requirements.txt

**Comment by treerink** [comment]
Unfortunately updating from CMOR release 3.2.5 to CMOR release 3.2.8 faces some dependency problems with non matching hdf5 and netcdf4 library versions. This issue starts after CMOR release 3.2.6. 

In the latest CMOR releases hdf5 1.8.18 is used with libnetcdf 4.4.*. But conda's netcdf4 itself needs hdf5 1.8.17. Netcdf4 is used by ece2cmor3.

**Comment by goord** [comment]
I managed to create an environment with netcdf4-3.1 and cmor-3.2.8 which both use hdf5-1.8.18, but then I get problems with cdo, which uses hdf5-1.8.17. This latter dependence is not listed as an anaconda dependence though, so that configuration just yield a broken cdo package.

I will ask the cmor team if they can make a conda package with hdf5-1.8.17.
